/* Sentinel Trade: scanner local, deliberadamente sem execução de ordens. */
window.__SENTINEL_VERSION = SentinelCore.VERSION;
const API = {
  cg: 'https://api.coingecko.com/api/v3',
  binance: SentinelCore.SOURCES.spot,
  futures: 'https://fapi.binance.com/fapi/v1',
  mexc: 'https://api.mexc.com/api/v3'
};
const state = { signals: [], signalHistory: loadSignalHistory(), activeSetup: null, trades: loadTrades(), importedTrades: loadImportedTrades(), closedMexcPositions: loadClosedMexcPositions(), mexcBalanceSnapshots: loadMexcBalanceSnapshots(), mexcBalanceUsdt: null, mexcPositions: [], autoTimer: null, tradeTrackingTimer: null, mexcLiveTimer: null, mexcHistoryTimer: null, usdBrl: 0, universeMode: 'market cap' };
const $ = (id) => document.getElementById(id);
const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'USD', maximumFractionDigits: value < 1 ? 5 : 2 }).format(value || 0);
const num = (value, digits = 2) => Number(value || 0).toLocaleString('pt-BR', { maximumFractionDigits: digits });
const tone = value => Number(value) > 0 ? 'positive' : Number(value) < 0 ? 'negative' : 'zero';
const nowLocal = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);

function loadTrades() { try { return JSON.parse(localStorage.getItem('radar-cripto-trades') || '[]'); } catch { return []; } }
function saveTrades() { localStorage.setItem('radar-cripto-trades', JSON.stringify(state.trades)); renderTrades(); renderStats(); }
function loadSignalHistory() {
  try {
    const raw = JSON.parse(localStorage.getItem('sentinel-trade-signal-history') || '[]'), seen = new Set();
    return raw.filter(item => {
      const key = `${item.symbol}|${item.strategyName}|${Number(item.entry).toFixed(10)}|${String(item.emittedAt || '').slice(0, 13)}`;
      if (seen.has(key)) return false;
      seen.add(key); return true;
    });
  } catch { return []; }
}
function saveSignalHistory() { localStorage.setItem('sentinel-trade-signal-history', JSON.stringify(state.signalHistory)); renderSignalHistory(); }
function loadImportedTrades() { try { return JSON.parse(localStorage.getItem('radar-cripto-mexc-imports') || '[]'); } catch { return []; } }
function saveImportedTrades() { localStorage.setItem('radar-cripto-mexc-imports', JSON.stringify(state.importedTrades)); renderImportedTrades(); renderMexcMetrics(); }
function loadClosedMexcPositions() { try { return JSON.parse(localStorage.getItem('sentinel-trade-mexc-closed-positions') || '[]'); } catch { return []; } }
function saveClosedMexcPositions() { localStorage.setItem('sentinel-trade-mexc-closed-positions', JSON.stringify(state.closedMexcPositions)); renderMexcMetrics(); }
function loadMexcBalanceSnapshots() { try { return JSON.parse(localStorage.getItem('sentinel-trade-mexc-balance-snapshots') || '[]'); } catch { return []; } }
function saveMexcBalanceSnapshots() { localStorage.setItem('sentinel-trade-mexc-balance-snapshots', JSON.stringify(state.mexcBalanceSnapshots)); }
function balancePeriod(date) { const d = new Date(date), day = String(d.getDate()).padStart(2, '0'), month = String(d.getMonth() + 1).padStart(2, '0'); return { week: `${d.getFullYear()}-${month}-S${Math.ceil(d.getDate() / 7)}`, month: `${d.getFullYear()}-${month}`, day }; }
function renderMexcBalanceHistory() { const rows = [...state.mexcBalanceSnapshots].sort((a, b) => new Date(b.at) - new Date(a.at)).slice(0, 24); $('mexcBalanceHistoryBody').innerHTML = rows.length ? rows.map((row, index) => { const previous = rows[index + 1], delta = previous ? row.usdt - previous.usdt : null; return `<tr><td>${row.week}</td><td>${row.month}</td><td>${new Date(row.at).toLocaleString('pt-BR')}</td><td>US$ ${num(row.usdt)}</td><td>R$ ${num(row.brl)}</td><td class="${delta == null || delta >= 0 ? 'positive' : 'negative'}">${delta == null ? '—' : `${delta >= 0 ? '+' : ''}US$ ${num(delta)}`}</td></tr>`; }).join('') : '<tr><td colspan="6" class="empty">Atualize as posições para registrar o primeiro saldo.</td></tr>'; }
function recordMexcBalance(data) { const usdt = +data.totalUsdt || 0; if (!usdt) return; const at = new Date().toISOString(), period = balancePeriod(at), current = state.mexcBalanceSnapshots.find(row => row.week === period.week); const snapshot = { ...period, at, usdt, brl: usdt * (state.usdBrl || 0) }; if (current) Object.assign(current, snapshot); else state.mexcBalanceSnapshots.push(snapshot); saveMexcBalanceSnapshots(); renderMexcBalanceHistory(); }
if (localStorage.getItem('sentinel-trade-signal-history-reset-v2') !== 'done') { state.signalHistory = []; localStorage.setItem('sentinel-trade-signal-history', '[]'); localStorage.setItem('sentinel-trade-signal-history-reset-v2', 'done'); }
function parseImportedNumber(value) { return Number(String(value ?? '').replace(/\./g, '').replace(',', '.')) || 0; }
function normalizeLegacyMexcTrade(trade) { if (trade.vehicle !== 'FUTURES' || trade.side != null) return trade; const side = +(String(trade.note || '').match(/Ordem\s+(\d+)/i) || [])[1] || 0, pnl = parseImportedNumber((String(trade.note || '').match(/PnL\s+(-?[\d.,]+)/i) || [])[1]); return { ...trade, side, realizedPnl: pnl, netPnl: pnl, legacy: true }; }
state.importedTrades = state.importedTrades.map(normalizeLegacyMexcTrade);
localStorage.setItem('radar-cripto-mexc-imports', JSON.stringify(state.importedTrades));
function setStatus(text, tone = 'neutral') { const el = $('connection'); el.textContent = text; el.className = `pill ${tone}`; }
function loadSettings() { try { return JSON.parse(localStorage.getItem('radar-cripto-settings') || '{}'); } catch { return {}; } }
function saveSettings() { localStorage.setItem('radar-cripto-settings', JSON.stringify({ autoRefresh: $('autoRefresh').value, browserAlerts: $('browserAlerts').checked })); }
function loadMexcCredentials() { try { return JSON.parse(localStorage.getItem('radar-cripto-mexc-credentials') || '{}'); } catch { return {}; } }
function saveMexcCredentials(credentials) { localStorage.setItem('radar-cripto-mexc-credentials', JSON.stringify(credentials)); }
function forgetMexcCredentials() { localStorage.removeItem('radar-cripto-mexc-credentials'); $('mexcApiKey').value = ''; $('mexcSecret').value = ''; $('mexcRemember').checked = false; $('mexcStatus').textContent = 'Chaves removidas deste navegador.'; }
function configureAutoRefresh() { clearInterval(state.autoTimer); const minutes = +$('autoRefresh').value, label = minutes >= 60 ? `a cada ${minutes / 60} ${minutes === 60 ? 'hora' : 'horas'}` : `a cada ${minutes} min`; saveSettings(); if (minutes) { state.autoTimer = setInterval(() => { if (!$('scanButton').disabled) scan(); }, minutes * 60000); $('scanStatus').textContent = `Atualização automática ativada: ${label} enquanto esta página estiver aberta.`; } }
function notifyNewSignals(signals) {
  if (!$('browserAlerts').checked || !('Notification' in window) || Notification.permission !== 'granted') return;
  let notified; try { notified=JSON.parse(localStorage.getItem('radar-cripto-notified')||'{}'); } catch { notified={}; }
  const now=Date.now(); signals.forEach(signal=>{const previous=notified[signal.symbol]; if(SentinelCore.isFresh(signal,typeof previous==='number'?{at:previous,entry:signal.entry}:previous,now)){ new Notification(`Sentinel Trade · LONG ${signal.symbol.replace('USDT','')}`,{body:`${signal.score}/100 | ${signal.trigger} | Entrada ${money(signal.entry)}`}); notified[signal.symbol]={at:now,entry:signal.entry,candleTime:signal.candleTime}; }});
  localStorage.setItem('radar-cripto-notified',JSON.stringify(notified));
}
const { last,sma,ema,rsi,atr,macd,adx,stochRsi,candlePattern,bullishPivot,supportResistance,weeklyExtension,analyseTimeframe,lateEntry } = SentinelCore;
function readCandles(raw) { return SentinelCore.closedCandles(raw); }
async function getJson(url) {
  const publicSource = [API.cg, API.binance, API.futures, SentinelCore.SOURCES.cmc, SentinelCore.SOURCES.okx, SentinelCore.SOURCES.kucoin].some(base => url.startsWith(base));
  const requestUrl = publicSource ? `/api/public?url=${encodeURIComponent(url)}` : url;
  const response = await fetch(requestUrl);
  if (!response.ok) { let detail = ''; try { detail = (await response.json()).error || ''; } catch {} throw new Error(detail || `Fonte respondeu ${response.status}`); }
  return response.json();
}
async function universe(maxAssets=1000) { const result=await SentinelCore.marketUniverse(getJson,{assetLimit:maxAssets,minVolume:+$('volumeLimit').value}); state.universeMode=result.mode; return result.assets; }
function resampleCandles(candles, hours) { const buckets = new Map(); for (const c of candles) { const time = Math.floor(c.time / (hours * 3600000)) * hours * 3600000, old = buckets.get(time); buckets.set(time, old ? { ...old, high: Math.max(old.high, c.high), low: Math.min(old.low, c.low), close: c.close, volume: old.volume + c.volume, takerBuyVolume: old.takerBuyVolume == null || c.takerBuyVolume == null ? null : old.takerBuyVolume + c.takerBuyVolume } : { ...c, time }); } return [...buckets.values()]; }
async function candles(asset, interval) { if (asset.source !== 'MEXC') return readCandles(await getJson(`${API.binance}/klines?symbol=${asset.symbol}&interval=${interval}&limit=210`)); const mexcInterval = interval === '1w' ? '1W' : interval === '2h' ? '1h' : interval, raw = await getJson(`${API.mexc}/klines?symbol=${asset.symbol}&interval=${mexcInterval}&limit=${interval === '2h' ? 500 : 210}`), parsed = readCandles(raw); return interval === '2h' ? resampleCandles(parsed, 2).slice(-210) : parsed; }
async function futuresCandles(symbol, interval) { return readCandles(await getJson(`${API.futures}/klines?symbol=${symbol}&interval=${interval}&limit=210`)); }
const { pullbackStochCriteria, aggressivePullbackCriteria, pullback1hConfirmationCriteria } = SentinelCore;
const SCANNER_TRIGGER_TIMEFRAMES = ['2h'];
const TRIGGER_TIMEFRAME_LABELS = { '1h': '1H · antecipado', '2h': '2H · intermediário', '4h': '4H · confirmação' };
const TRIGGER_TIMEFRAME_RANK = { '1h': 0, '2h': 1, '4h': 2, '1d': 3 };
async function inspect(asset, selectedStrategy='trend', triggerTimeframe='2h') { const clock=await getJson(`${API.binance}/time`), source=asset.source==='OKX'?SentinelCore.SOURCES.okx:(asset.source==='KUCOIN'?SentinelCore.SOURCES.kucoin:SentinelCore.SOURCES.spot), series=await SentinelCore.fetchSeries(getJson,asset.exchangeSymbol||asset.symbol,clock.serverTime,source); return SentinelCore.evaluateAnalyses(asset,series,SentinelCore.analyseSet(series),selectedStrategy,{minScore:+$('minScore').value},triggerTimeframe); }
async function chooseVehicle(signal) { return SentinelCore.vehicle(getJson,signal,Date.now()); }
async function concurrentMap(items, limit, worker, onProgress) {
  const results = []; let next = 0;
  async function runner() { while (next < items.length) { const index = next++; try { const result = await worker(items[index]); if (result) results.push(result); } catch { /* ativo indisponível ou limitador da fonte */ } onProgress(index + 1, items.length); } }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, runner)); return results;
}
async function scan() {
  $('scanButton').disabled=true; $('scanButton').textContent='Analisando…'; setStatus('Consultando mercado','warn');
  try {
    const config=SentinelCore.settings({minScore:+$('minScore').value,minVolume:+$('volumeLimit').value,assetLimit:+$('assetLimit').value,strategy:$('strategySelect').value});
    const result=await SentinelCore.scanMarket(getJson,config,(done,total)=>$('scanStatus').textContent=`Analisando ${done}/${total} ativos com as mesmas regras do Telegram…`);
    const active=new Set(state.trades.filter(t=>!t.imported&&!t.result).map(t=>t.symbol));
    const hidden=result.signals.filter(s=>active.has(s.symbol)).length;
    state.signals=result.signals.filter(s=>!active.has(s.symbol));
    notifyNewSignals(state.signals); renderSignals(); renderStats();
    const issues=result.failures.length ? ` ${result.failures.length} ativo(s) com falha de consulta: ${result.failures.slice(0,3).map(f=>f.symbol).join(', ')}.` : '';
    $('scanStatus').textContent=`Concluído: ${result.assets} ativo(s), ranking ${result.mode}, score ≥${config.minScore}, volume do par ≥${money(config.minVolume)}. Fontes: Binance / OKX; gatilho 2H fechado. ${hidden} ativo(s) já em acompanhamento.${issues}${result.warnings.length ? ' Avisos: '+result.warnings.slice(0,3).join(' | ') : ''}`;
    setStatus(result.failures.length||result.warnings.length?'Consulta com avisos':'Mercado atualizado',result.failures.length||result.warnings.length?'warn':'good');
  } catch(error) { state.signals=[]; renderSignals(); renderStats(); $('scanStatus').textContent=`Não foi possível concluir: ${error.message}`; setStatus('Falha na consulta','bad'); }
  finally { $('scanButton').disabled=false; $('scanButton').textContent='Atualizar scanner'; }
}
function renderSignals() {
  $('signalsBody').innerHTML = state.signals.length ? state.signals.map((s, i) => `<tr class="${i === 0 ? 'best-setup' : ''}"><td><div class="asset">${s.symbol.replace('USDT', '')} ${i === 0 ? '<span class="best-badge">★ MELHOR OPÇÃO</span>' : ''}</div><div class="sub">${SentinelCore.rankingLabel(s)} · ${s.name}</div><div class="exchange-badge ${String(s.source).toLowerCase()}">CORRETORA: ${s.source}</div><div class="vehicle-badge ${s.vehicle === 'FUTURES' ? 'futures' : ''}">MELHOR: ${s.vehicle === 'FUTURES' ? 'FUTUROS' : 'SPOT'}</div></td><td><span class="score">${s.score}/100</span><div class="sub"><span class="timeframe-badge tf-${s.triggerTimeframe || '1h'}">GATILHO ${s.triggerLabel || String(s.triggerTimeframe || '1h').toUpperCase()}</span></div><div class="sub strategy-name"><strong>${s.strategyName}</strong></div><div class="sub">LONG · <span class="tag ${s.vehicle === 'FUTURES' ? 'tp1' : 'live'}">${s.vehicle} ${s.leverage}</span></div><div class="sub">${s.vehicleReason}</div></td><td>${s.context}</td><td>${s.trigger}${s.resistance ? `<div class="sub">Resistência: ${money(s.resistance)} · espaço mínimo validado</div>` : ''}</td><td>${money(s.entry)}</td><td>${money(s.stop)}<div class="sub">Risco ${num((s.entry-s.stop)/s.entry*100)}%</div></td><td>${money(s.tp2)} <span class="tag tp1">2R</span><br>${money(s.tp3)} <span class="tag tp2">3R</span></td><td><button class="primary mini" data-setup="${i}">Validar entrada</button></td></tr>`).join('') : '<tr><td colspan="8" class="empty">Nenhum setup passou pelos filtros. Isso é saudável: o scanner evita forçar operações.</td></tr>';
  document.querySelectorAll('#signalsBody tr').forEach((row, index) => { const cell = row.cells[0], signal = state.signals[index]; if (!cell || !signal || cell.querySelector('.direction-badge')) return; const badge = document.createElement('div'); const direction = signal.direction || 'LONG'; badge.className = `direction-badge ${direction.toLowerCase()}`; badge.textContent = direction; cell.insertBefore(badge, cell.children[2] || null); });
  document.querySelectorAll('[data-setup]').forEach(button => button.addEventListener('click', () => openEntry(state.signals[+button.dataset.setup])));
}
function registerSignals(signals) {
  const now = Date.now();
  signals.forEach(signal => {
    const existing = state.signalHistory.find(item => item.symbol === signal.symbol && item.strategyName === signal.strategyName && Math.abs(Number(item.entry) - Number(signal.entry)) / Math.max(Number(signal.entry), 1e-12) < 0.002 && now - new Date(item.emittedAt || 0).getTime() < 6 * 60 * 60 * 1000);
    if (!existing) state.signalHistory.unshift({ ...signal, id: crypto.randomUUID(), emittedAt: new Date(now).toISOString(), status: 'open', result: null, currentPrice: signal.entry, hitAt: null });
  });
  state.signalHistory = state.signalHistory.slice(0, 500);
  saveSignalHistory();
}
function renderSignalHistory() {
  if (!$('signalHistoryMetrics')) return;
  const history = state.signalHistory || [], closed = history.filter(item => item.result), wins = closed.filter(item => item.result === 'win'), losses = closed.filter(item => item.result === 'loss'), avg = values => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0, winReturns = wins.map(item => Number(item.returnPct) || 0), lossReturns = losses.map(item => Number(item.returnPct) || 0), validated = state.trades.filter(trade => !trade.imported), metrics = [['Sinais detectados', history.length], ['Entradas validadas por você', validated.length], ['Wins / losses técnicos', `${wins.length} / ${losses.length}`], ['Assertividade técnica', closed.length ? `${num(wins.length / closed.length * 100, 1)}%` : '—'], ['Gain médio até TP 2R', winReturns.length ? `+${num(avg(winReturns))}%` : '—'], ['Loss médio', lossReturns.length ? `${num(avg(lossReturns))}%` : '—']];
  $('signalHistoryMetrics').innerHTML = metrics.map(([label, value]) => `<div class="stat"><div class="muted">${label}</div><div class="value">${value}</div></div>`).join('');
  const byStrategy = new Map(); history.forEach(item => { const key = item.strategyName || 'Setup técnico', bucket = byStrategy.get(key) || { total: 0, wins: 0, losses: 0, returns: [] }; bucket.total++; if (item.result === 'win') bucket.wins++; if (item.result === 'loss') bucket.losses++; if (Number.isFinite(Number(item.returnPct))) bucket.returns.push(Number(item.returnPct)); byStrategy.set(key, bucket); });
  $('signalStrategyStatsBody').innerHTML = byStrategy.size ? [...byStrategy.entries()].map(([name, bucket]) => { const decided = bucket.wins + bucket.losses, average = bucket.returns.length ? bucket.returns.reduce((a, b) => a + b, 0) / bucket.returns.length : 0; return `<tr><td>${name}</td><td>${bucket.total}</td><td class="positive">${bucket.wins}</td><td class="negative">${bucket.losses}</td><td>${decided ? `${num(bucket.wins / decided * 100, 1)}%` : '—'}</td><td class="${average >= 0 ? 'positive' : 'negative'}">${bucket.returns.length ? `${average >= 0 ? '+' : ''}${num(average)}%` : '—'}</td></tr>`; }).join('') : '<tr><td colspan="6" class="empty">Aguardando sinais.</td></tr>';
  $('signalHistoryBody').innerHTML = history.length ? history.map(item => { const label = item.result === 'win' ? 'WIN · TP 2R' : item.result === 'loss' ? 'LOSS · Stop' : 'Em acompanhamento'; const statusTone = item.result === 'win' ? 'live' : item.result === 'loss' ? 'loss' : 'closed', source = String(item.source || '—'), vehicle = item.vehicle === 'FUTURES' ? 'FUTUROS' : 'SPOT'; return `<tr><td><div class="asset">${String(item.symbol).replace('USDT', '')}</div><div class="sub">${new Date(item.emittedAt).toLocaleString('pt-BR')}</div></td><td>${item.strategyName || 'Setup técnico'}<div class="exchange-badge ${source.toLowerCase()}">CORRETORA: ${source}</div><div class="vehicle-badge ${vehicle === 'FUTUROS' ? 'futures' : ''}">MELHOR: ${vehicle}</div><div class="sub">Score ${item.score || '—'}</div></td><td>${money(item.entry)} / ${money(item.stop)}</td><td>${money(item.tp2)} <span class="tag tp1">2R</span><br>${money(item.tp3)} <span class="tag tp2">3R</span></td><td><span class="tag ${statusTone}">${label}</span><div class="sub">${item.hitAt ? new Date(item.hitAt).toLocaleString('pt-BR') : item.currentPrice ? `Agora ${money(item.currentPrice)}` : 'Aguardando preço'}</div></td><td class="${tone(item.returnPct)}">${Number.isFinite(Number(item.returnPct)) ? `${Number(item.returnPct) > 0 ? '+' : ''}${num(item.returnPct)}%` : '—'}</td></tr>`; }).join('') : '<tr><td colspan="6" class="empty">Ainda não há sinais emitidos.</td></tr>';
}
async function refreshSignalHistory() {
  const pending = state.signalHistory.filter(item => item.status === 'open');
  if (!pending.length) { renderSignalHistory(); return; }
  await concurrentMap(pending, 4, async item => {
    const source = item.source === 'MEXC' ? API.mexc : API.binance;
    const candlesRaw = await getJson(`${source}/klines?symbol=${item.symbol}&interval=1h&limit=6`), candlesNow = readCandles(candlesRaw), lastCandle = candlesNow.at(-1);
    if (!lastCandle) return;
    item.currentPrice = lastCandle.close;
    const hitStop = candlesNow.some(candle => candle.low <= item.stop), hitTarget = candlesNow.some(candle => candle.high >= item.tp2);
    if (hitStop) { item.result = 'loss'; item.status = 'closed'; item.returnPct = (item.stop - item.entry) / item.entry * 100; item.hitAt = new Date().toISOString(); }
    else if (hitTarget) { item.result = 'win'; item.status = 'closed'; item.returnPct = (item.tp2 - item.entry) / item.entry * 100; item.hitAt = new Date().toISOString(); }
  }, () => {});
  saveSignalHistory();
  if ($('signalHistoryStatus')) $('signalHistoryStatus').textContent = `Atualizado às ${new Date().toLocaleTimeString('pt-BR')}. O WIN técnico é marcado quando o preço toca o primeiro alvo (TP 2R), mesmo que você não tenha validado a entrada.`;
}
function openEntry(setup) { state.activeSetup = setup; $('entrySetup').innerHTML = `<strong>${setup.symbol}</strong> · ${setup.strategyName} · ${setup.direction || 'LONG'} ${setup.score}/100 · ${setup.vehicle} ${setup.leverage}<br>${setup.vehicleReason}<br>Referência: ${money(setup.entry)} | Stop: ${money(setup.stop)} | TP 2R: ${money(setup.tp2)} | TP 3R: ${money(setup.tp3)}`; $('executedPrice').value = setup.entry; $('tradeNotional').value = ''; $('entryTime').value = nowLocal(); $('tradeNote').value = ''; $('entryDialog').showModal(); }
function recordTrade(event) { event.preventDefault(); const s = state.activeSetup, entry = +$('executedPrice').value; if (!s || !entry) return; state.trades.unshift({ id: crypto.randomUUID(), symbol: s.symbol, name: s.name, source: s.source, exchangeSymbol: s.exchangeSymbol, strategyName: s.strategyName, triggerTimeframe: s.triggerTimeframe || '1h', vehicle: s.vehicle, leverage: s.leverage, entry, notionalUsd: +$('tradeNotional').value || 0, stop: s.stop, tp2: s.tp2, tp3: s.tp3, openedAt: $('entryTime').value, note: $('tradeNote').value.trim(), status: 'open', result: null, currentPrice: entry }); state.signals = state.signals.filter(signal => signal.symbol !== s.symbol); saveTrades(); registerSignals([{ ...s, entry }]); renderSignals(); renderStats(); $('entryDialog').close(); }
function tradeReturn(trade, price) { return (price - trade.entry) / trade.entry * 100; }
function renderTrades() {
  $('tradesBody').innerHTML = state.trades.length ? state.trades.map(t => { const imported = t.imported, price = t.currentPrice || t.entry, pnl = imported ? null : t.result === 'loss' ? tradeReturn(t, t.stop) : t.result === 'tp2' ? tradeReturn(t, t.tp2) : t.result === 'tp3' ? tradeReturn(t, t.tp3) : tradeReturn(t, price), label = imported ? 'Importado (leitura)' : t.result === 'loss' ? 'Stop atingido' : t.result === 'tp2' ? 'TP 2R atingido' : t.result === 'tp3' ? 'TP 3R atingido' : 'Em acompanhamento'; return `<tr><td><div class="asset">${t.symbol.replace('USDT','')}</div><div class="sub">${t.strategyName || 'Tendência + pivô'}</div><div class="sub">${t.vehicle || 'SPOT'} ${t.leverage || '1×'} · ${t.note || 'Sem observação'}</div></td><td>${money(t.entry)}<div class="sub">${new Date(t.openedAt).toLocaleString('pt-BR')}</div></td><td>${imported ? '—' : `${money(t.stop)} / ${money(t.tp2)} / ${money(t.tp3)}`}</td><td><span class="tag ${imported ? 'closed' : t.result === 'loss' ? 'loss' : t.result ? 'closed' : 'live'}">${label}</span></td><td class="${pnl == null ? '' : tone(pnl)}">${pnl == null ? '—' : `${pnl > 0 ? '+' : ''}${num(pnl)}%`}</td><td>${imported ? 'Histórico MEXC' : t.result ? 'Encerrada' : `${money(price)} agora`}</td><td>${imported ? '' : t.result ? `<button class="secondary mini" data-reopen="${t.id}">Reabrir</button>` : `<button class="secondary mini" data-result="tp2" data-id="${t.id}">TP 2R</button> <button class="secondary mini" data-result="tp3" data-id="${t.id}">TP 3R</button> <button class="secondary mini danger" data-result="loss" data-id="${t.id}">Stop</button>`}<button class="secondary mini danger" data-delete="${t.id}">×</button></td></tr>`; }).join('') : '<tr><td colspan="7" class="empty">Valide uma entrada em um setup para começar o histórico.</td></tr>';
  document.querySelectorAll('[data-result]').forEach(b => b.addEventListener('click', () => closeTrade(b.dataset.id, b.dataset.result)));
  document.querySelectorAll('[data-reopen]').forEach(b => b.addEventListener('click', () => { const t = state.trades.find(x => x.id === b.dataset.reopen); t.result = null; t.status = 'open'; saveTrades(); }));
  document.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', () => { state.trades = state.trades.filter(t => t.id !== b.dataset.delete); saveTrades(); }));
}
function renderImportedTrades() { $('importedTradesBody').innerHTML = state.importedTrades.length ? state.importedTrades.map(t => `<tr><td><div class="asset">${t.symbol.replace('USDT', '')}</div><div class="sub">MEXC</div></td><td>${t.vehicle} ${t.leverage}</td><td>${money(t.entry)}</td><td>${new Date(t.openedAt).toLocaleString('pt-BR')}</td><td>${t.note}</td></tr>`).join('') : '<tr><td colspan="5" class="empty">Nenhuma operação importada nesta sessão.</td></tr>'; }
function renderMexcMetrics() {
  const imported = state.importedTrades, futures = imported.filter(t => t.vehicle === 'FUTURES');
  const fallback = futures.filter(t => t.side === 2 || t.side === 4).map(t => ({ id: t.id, symbol: t.name || t.symbol, direction: t.side === 4 ? 'LONG' : 'SHORT', leverage: parseFloat(t.leverage) || 1, entry: t.entry, exit: t.entry, margin: 0, pnlUsd: Number.isFinite(t.netPnl) ? t.netPnl : (t.realizedPnl || 0), returnPct: t.pnlOnNotional ?? null, closedAt: t.openedAt }));
  // A MEXC pode atualizar fills antes do endpoint de posições históricas. Combina os dois
  // retornos e só acrescenta um fill quando não há posição equivalente já registrada.
  const normalizedSymbol = value => String(value || '').replace('_USDT', '').toUpperCase();
  const equivalent = (a, b) => normalizedSymbol(a.symbol) === normalizedSymbol(b.symbol)
    && Math.abs((Number(a.pnlUsd) || 0) - (Number(b.pnlUsd) || 0)) < 0.02
    && Math.abs(new Date(a.closedAt).getTime() - new Date(b.closedAt).getTime()) < 6 * 60 * 60 * 1000;
  const historical = state.closedMexcPositions.slice();
  const allClosed = [...historical, ...fallback.filter(fill => Math.abs(Number(fill.pnlUsd) || 0) > 0 && !historical.some(position => equivalent(position, fill)))];
  // A MEXC não devolve de forma confiável o valor monetário do SL depois do fechamento.
  // Usamos o resultado absoluto como proxy transparente para não misturar microtestes às métricas.
  const minResult = Math.max(0, Number($('mexcMinResult')?.value) || 0);
  const cutoff = new Date('2026-09-10T00:00:00-03:00').getTime();
  const closed = allClosed.filter(position => new Date(position.closedAt).getTime() >= cutoff && Math.abs(Number(position.pnlUsd) || 0) >= minResult);
  const excluded = allClosed.length - closed.length;
  const sum = values => values.reduce((total, value) => total + value, 0), average = values => values.length ? sum(values) / values.length : 0, wins = closed.filter(position => position.pnlUsd > 0), losses = closed.filter(position => position.pnlUsd < 0), totalGain = sum(wins.map(position => position.pnlUsd)), totalLoss = sum(losses.map(position => position.pnlUsd)), net = totalGain + totalLoss;
  const returns = closed.map(position => position.returnPct).filter(Number.isFinite), winReturns = returns.filter(value => value > 0), lossReturns = returns.filter(value => value < 0), leverage = closed.map(position => +position.leverage).filter(Number.isFinite), volume = sum(imported.map(t => +t.executedValue || 0));
  const primary = [
    ['Operações fechadas', closed.length],
    ['Acertos / erros', `${wins.length} / ${losses.length}`],
    ['Alavancagem média', leverage.length ? `${num(average(leverage), 1)}×` : '—'],
    ['Taxa de acerto', wins.length + losses.length ? `${num(wins.length / (wins.length + losses.length) * 100, 1)}%` : '—'],
    ['Saldo atual (US$)', Number.isFinite(state.mexcBalanceUsdt) ? 'US$ ' + num(state.mexcBalanceUsdt) : (state.mexcBalanceSnapshots[0] ? 'US$ ' + num(state.mexcBalanceSnapshots[0].usdt) : 'Atualize o saldo')],
    ['Saldo atual (R$)', state.mexcBalanceUsdt && state.usdBrl ? 'R$ ' + num(state.mexcBalanceUsdt * state.usdBrl) : (state.mexcBalanceSnapshots[0] ? 'R$ ' + num(state.mexcBalanceSnapshots[0].brl) : 'Atualize o saldo')]
  ];
  const gainAverage = wins.length ? average(wins.map(position => position.pnlUsd)) : 0;
  const lossAverage = losses.length ? average(losses.map(position => position.pnlUsd)) : 0;
  const performance = [
    ['Total de ganhos (US$)', `+US$ ${num(totalGain)}`, 'gain'],
    ['Gain médio (US$)', wins.length ? `+US$ ${num(gainAverage)}` : '—', 'gain'],
    ['Loss médio (US$)', losses.length ? `US$ ${num(lossAverage)}` : '—', 'loss'],
    ['Total de perdas (US$)', `US$ ${num(totalLoss)}`, 'loss'],
    ['Resultado líquido', `${net >= 0 ? '+' : ''}US$ ${num(net)}`, net >= 0 ? 'gain' : 'loss'],
    ['Gain médio (%)', winReturns.length ? `+${num(average(winReturns))}%` : '—', 'gain'],
    ['Loss médio (%)', lossReturns.length ? `${num(average(lossReturns))}%` : '—', 'loss']
  ];
  const card = ([label, value, tone]) => `<div class="stat ${tone ? `mexc-metric-${tone}` : ''}"><div class="muted">${label}</div><div class="value">${value}</div></div>`;
  $('mexcMetricsPrimary').innerHTML = primary.map(card).join('');
  $('mexcMetricsPerformance').innerHTML = performance.map(card).join('');
  $('mexcResultsBody').innerHTML = closed.length ? closed.map(position => `<tr><td><div class="asset">${String(position.symbol).replace('_USDT', '')}</div><div class="sub">${new Date(position.closedAt).toLocaleString('pt-BR')}</div></td><td>${position.direction} · ${position.leverage}×</td><td>${money(position.entry)} → ${money(position.exit)}</td><td>${position.margin ? `US$ ${num(position.margin)}` : '—'}</td><td class="${position.pnlUsd >= 0 ? 'positive' : 'negative'}">${position.pnlUsd >= 0 ? '+' : ''}US$ ${num(position.pnlUsd)}</td><td class="${position.returnPct >= 0 ? 'positive' : 'negative'}">${Number.isFinite(position.returnPct) ? `${position.returnPct >= 0 ? '+' : ''}${num(position.returnPct)}%` : '—'}</td><td><span class="tag ${position.pnlUsd >= 0 ? 'live' : 'loss'}">${position.pnlUsd >= 0 ? 'WIN' : 'LOSS'}</span></td></tr>`).join('') : '<tr><td colspan="7" class="empty">Nenhuma posição fechada atingiu o resultado mínimo configurado.</td></tr>';
  const byAsset = new Map(); closed.forEach(position => { const asset = normalizedSymbol(position.symbol), bucket = byAsset.get(asset) || { total: 0, wins: 0, losses: 0, gain: 0, loss: 0 }; bucket.total++; if (position.pnlUsd > 0) { bucket.wins++; bucket.gain += position.pnlUsd; } else if (position.pnlUsd < 0) { bucket.losses++; bucket.loss += position.pnlUsd; } byAsset.set(asset, bucket); });
  $('mexcResultsBody').innerHTML = byAsset.size ? [...byAsset.entries()].sort((a, b) => (b[1].gain + b[1].loss) - (a[1].gain + a[1].loss)).map(([asset, bucket]) => { const netAsset = bucket.gain + bucket.loss, decided = bucket.wins + bucket.losses; return `<tr><td><strong>${asset}</strong></td><td>${bucket.total}</td><td class="result-win">${bucket.wins}</td><td class="result-loss">${bucket.losses}</td><td>${decided ? `${num(bucket.wins / decided * 100, 1)}%` : '—'}</td><td class="positive">+US$ ${num(bucket.gain)}</td><td class="negative">US$ ${num(bucket.loss)}</td><td class="${netAsset >= 0 ? 'positive' : 'negative'}">${netAsset >= 0 ? '+' : ''}US$ ${num(netAsset)}</td></tr>`; }).join('') : '<tr><td colspan="8" class="empty">Nenhuma operação fechada atingiu o resultado mínimo configurado.</td></tr>';
  $('mexcMetricsNote').textContent = `Corte aplicado: operações encerradas desde 10/09/2026 e resultado absoluto mínimo de US$ ${num(minResult)}. ${excluded} registro(s) ficaram fora do resumo; o detalhamento bruto permanece oculto.`;
}
function mexcCredentials() { const saved = loadMexcCredentials(); return { apiKey: $('mexcApiKey').value.trim() || saved.apiKey || '', secret: $('mexcSecret').value.trim() || saved.secret || '' }; }
function renderMexcPositions() { const positions = state.mexcPositions, totalPnl = positions.reduce((sum, position) => sum + position.pnlUsd, 0), totalMargin = positions.reduce((sum, position) => sum + position.margin, 0), roi = totalMargin ? totalPnl / totalMargin * 100 : 0, metrics = [['Posições abertas', positions.length], ['Margem usada', `US$ ${num(totalMargin)}`], ['PnL em aberto', `${totalPnl >= 0 ? '+' : ''}US$ ${num(totalPnl)}`], ['PnL em reais', `${totalPnl >= 0 ? '+' : ''}R$ ${num(totalPnl * state.usdBrl)}`], ['Retorno sobre margem', totalMargin ? `${roi >= 0 ? '+' : ''}${num(roi)}%` : '—'], ['USDT / BRL', state.usdBrl ? `R$ ${num(state.usdBrl, 4)}` : '—']]; $('mexcLiveMetrics').innerHTML = metrics.map(([label, value]) => `<div class="stat"><div class="muted">${label}</div><div class="value ${totalPnl < 0 && label.includes('PnL') ? 'negative' : ''}">${value}</div></div>`).join(''); $('mexcPositionsBody').innerHTML = positions.length ? positions.map(position => `<tr><td><div class="asset">${position.symbol.replace('_USDT', '')}</div><div class="sub">${position.direction} · ${position.mode}</div></td><td>${money(position.entry)} → ${money(position.current)}<div class="sub">${position.changePct >= 0 ? '+' : ''}${num(position.changePct)}%</div></td><td>${position.leverage}×<div class="sub">Margem US$ ${num(position.margin)}</div></td><td class="${position.pnlUsd >= 0 ? 'positive' : 'negative'}">${position.pnlUsd >= 0 ? '+' : ''}US$ ${num(position.pnlUsd)}<div class="sub">${position.pnlUsd >= 0 ? '+' : ''}R$ ${num(position.pnlUsd * state.usdBrl)}</div></td><td>SL: ${position.stop ? money(position.stop) : 'Não informado'}<br>TP: ${position.target ? money(position.target) : 'Não informado'}</td><td>${position.liquidation ? money(position.liquidation) : '—'}</td><td><span class="tag live">Em andamento</span></td></tr>`).join('') : '<tr><td colspan="7" class="empty">Nenhuma posição de futuros em aberto na MEXC.</td></tr>'; }
async function refreshMexcPositions() { const { apiKey, secret } = mexcCredentials(); if (!apiKey || !secret) { $('mexcLiveStatus').textContent = 'Salve ou informe as chaves MEXC para acompanhar posições reais.'; return; } $('mexcPositionsButton').disabled = true; $('mexcPositionsButton').textContent = 'Atualizando…'; $('mexcLiveStatus').textContent = 'Consultando posições abertas e preços atuais, somente leitura…'; try { const response = await fetch('/api/mexc/positions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ apiKey, secret }) }), data = await response.json(); if (!response.ok) throw new Error(data.error || 'Falha ao consultar posições.'); const [brl] = await Promise.all([getJson(`${API.binance}/ticker/price?symbol=USDTBRL`).catch(() => ({ price: 0 }))]); state.usdBrl = +brl.price || state.usdBrl || 0; const sizes = new Map((data.contracts || []).map(contract => [contract.symbol, +contract.contractSize || 0])), tickers = new Map((data.tickers || []).map(ticker => [ticker.symbol, +ticker.lastPrice || +ticker.fairPrice || 0])), stops = new Map(); (data.stopOrders || []).forEach(order => { const old = stops.get(order.positionId) || {}; stops.set(order.positionId, { stop: +order.stopLossPrice || old.stop || 0, target: +order.takeProfitPrice || old.target || 0 }); }); state.mexcPositions = (data.positions || []).filter(position => +position.holdVol > 0).map(position => { const current = tickers.get(position.symbol) || +position.holdAvgPrice, entry = +position.holdAvgPrice || +position.openAvgPrice, direction = +position.positionType === 1 ? 'LONG' : 'SHORT', factor = direction === 'LONG' ? 1 : -1, notionalUnit = (+position.holdVol || 0) * (sizes.get(position.symbol) || 0), pnlUsd = (current - entry) * notionalUnit * factor, risk = stops.get(position.positionId) || {}; return { symbol: position.symbol, direction, mode: +position.openType === 1 ? 'Isolado' : 'Cruzado', entry, current, changePct: entry ? (current / entry - 1) * 100 * factor : 0, leverage: +position.leverage || 1, margin: +position.im || +position.oim || 0, pnlUsd, stop: risk.stop, target: risk.target, liquidation: +position.liquidatePrice || 0 }; }); renderMexcPositions(); $('mexcLiveStatus').textContent = `Atualizado às ${new Date().toLocaleTimeString('pt-BR')}. ${data.stopError ? `SL/TP indisponível: ${data.stopError}` : 'Preços e posições em acompanhamento.'}`; } catch (error) { $('mexcLiveStatus').textContent = `Não foi possível atualizar posições: ${error.message}`; } finally { $('mexcPositionsButton').disabled = false; $('mexcPositionsButton').textContent = 'Atualizar posições'; } }
async function refreshMexcBalanceSnapshot() { const { apiKey, secret } = mexcCredentials(); if (!apiKey || !secret) return; const [data, brl] = await Promise.all([fetch('/api/mexc/balance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ apiKey, secret }) }).then(response => response.ok ? response.json() : null).catch(() => null), getJson(`${API.binance}/ticker/price?symbol=USDTBRL`).catch(() => ({ price: 0 }))]); state.usdBrl = +brl.price || state.usdBrl || 0; if (data) { state.mexcBalanceUsdt = Number(data.totalUsdt); recordMexcBalance(data); renderMexcMetrics(); } }
async function refreshMexcHistoryPanel() { const button = $('mexcHistoryRefreshButton'); if (!button) return; button.disabled = true; button.textContent = 'Atualizando…'; try { await importMexcTrades(); await refreshMexcBalanceSnapshot(); } finally { button.disabled = false; button.textContent = 'Atualizar posições'; } }function configureMexcLive() { clearInterval(state.mexcLiveTimer); if ($('mexcLiveAuto').checked) state.mexcLiveTimer = setInterval(() => { refreshMexcPositions(); refreshMexcBalanceSnapshot(); }, 30000); }
function configureMexcHistoryAuto() { clearInterval(state.mexcHistoryTimer); if ($('mexcHistoryAuto').checked) state.mexcHistoryTimer = setInterval(() => { const { apiKey, secret } = mexcCredentials(); if (apiKey && secret && !$('mexcImportButton').disabled) { importMexcTrades(); refreshMexcBalanceSnapshot(); } }, 20000); }
function updateStrategyHelp() {
  const help = $('strategyHelp'); if (!help) return;
  const strategy = $('strategySelect').value;
  help.textContent = strategy === 'both' ? 'Executa os três critérios e mantém somente o sinal de maior score por ativo. Futuros limitados a 3×.' : strategy === 'trend' ? 'Critério mais amplo: tendência macro, pivôs e confirmação de fluxo. Futuros limitados a 3×.' : strategy === 'flexible-pullback-2h' ? 'Pullback 2H com confirmação 4H e diário flexível: menor peso do momentum diário, sem bloqueio diário rígido. Futuros limitados a 3×.' : 'Critério operacional: Pullback no 2H com confirmação de tendência no 4H. Futuros limitados a 3×.';
}
function closeTrade(id, result) { const trade = state.trades.find(t => t.id === id); if (!trade) return; trade.result = result; trade.status = 'closed'; trade.closedAt = new Date().toISOString(); saveTrades(); }
function renderStats() { const closed = state.trades.filter(t => t.result), wins = closed.filter(t => t.result !== 'loss'), losses = closed.filter(t => t.result === 'loss'), gains = wins.map(t => tradeReturn(t, t.result === 'tp3' ? t.tp3 : t.tp2)), downs = losses.map(t => tradeReturn(t, t.stop)); const avg = a => a.length ? a.reduce((x,y) => x+y,0)/a.length : 0; const cards = [['Setups atuais', state.signals.length], ['Entradas registradas', state.trades.length], ['Taxa de acerto', closed.length ? `${num(wins.length/closed.length*100,1)}%` : '—'], ['Gain médio', gains.length ? `+${num(avg(gains))}%` : '—'], ['Loss médio', downs.length ? `${num(avg(downs))}%` : '—']]; $('summaryCards').innerHTML = cards.map(([label,value]) => `<div class="stat"><div class="muted">${label}</div><div class="value">${value}</div></div>`).join(''); }
async function refreshTracking() { const open = state.trades.filter(t => !t.result); if (!open.length) return; $('refreshTracking').disabled = true; $('refreshTracking').textContent = 'Atualizando…'; try { await concurrentMap(open, 4, async t => { const source = t.vehicle === 'FUTURES' ? API.futures : t.source === 'MEXC' ? API.mexc : API.binance, data = t.source === 'OKX' ? await getJson(`${SentinelCore.SOURCES.okx}/market/ticker?instId=${encodeURIComponent(t.exchangeSymbol||t.symbol.replace(/USDT$/,'-USDT'))}`).then(result=>{if(String(result.code)!=='0'||!result.data?.[0])throw new Error('Preço OKX indisponível');return {price:result.data[0].last};}) : await getJson(`${source}/ticker/price?symbol=${t.symbol}`), price = +data.price; t.currentPrice = price; if (price <= t.stop) { t.result = 'loss'; t.status = 'closed'; } else if (price >= t.tp3) { t.result = 'tp3'; t.status = 'closed'; } else if (price >= t.tp2) { t.result = 'tp2'; t.status = 'closed'; } }, () => {}); saveTrades(); } catch { setStatus('Falha ao checar preços', 'bad'); } finally { $('refreshTracking').disabled = false; $('refreshTracking').textContent = 'Atualizar trades'; } }
function configureTradeTracking() { clearInterval(state.tradeTrackingTimer); if ($('tradeTrackingAuto')?.checked) state.tradeTrackingTimer = setInterval(() => { if (state.trades.some(trade => !trade.result)) refreshTracking(); }, 20000); }
$('tradeTrackingAuto')?.addEventListener('change', configureTradeTracking);
configureTradeTracking();
$('mexcPositionsButton')?.addEventListener('click', refreshMexcBalanceSnapshot); $('mexcHistoryRefreshButton')?.addEventListener('click', refreshMexcHistoryPanel);
renderMexcBalanceHistory();
async function importMexcTrades() {
  const apiKey = $('mexcApiKey').value.trim(), secret = $('mexcSecret').value.trim(), spotSymbol = $('mexcSpotSymbol').value.trim().toUpperCase(); if (!apiKey || !secret) { $('mexcStatus').textContent = 'Informe as duas chaves somente neste painel local.'; return; } if (location.protocol === 'file:') { $('mexcStatus').textContent = 'Abra pelo arquivo iniciar-painel.bat; o modo de arquivo não permite a importação privada.'; return; }
  if ($('mexcRemember').checked) saveMexcCredentials({ apiKey, secret, spotSymbol, remember: true }); else localStorage.removeItem('radar-cripto-mexc-credentials');
  $('mexcImportButton').disabled = true; $('mexcImportButton').textContent = 'Importando…'; $('mexcStatus').textContent = 'Consultando somente histórico de fills spot e ordens de futuros…';
  try { const response = await fetch('/api/mexc/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ apiKey, secret, spotSymbol }) }), raw = await response.text(); let data; try { data = JSON.parse(raw); } catch { throw new Error('O serviço local aberto não possui a integração MEXC atualizada. Abra o painel em http://127.0.0.1:4174.'); } if (!response.ok) throw new Error(data.error || 'Falha na importação.');
    const contractSizes = new Map((data.contracts || []).map(c => [c.symbol, +c.contractSize || 0]));
    const spot = data.spot.map(t => ({ id: `mexc-spot-${t.id}`, imported: true, symbol: t.symbol, name: t.symbol, source: 'MEXC', strategyName: 'Importado MEXC Spot', vehicle: 'SPOT', leverage: '1×', entry: +t.price, openedAt: new Date(t.time).toISOString(), note: `${t.isBuyer ? 'Compra' : 'Venda'} · ${t.qty}`, executedValue: +(t.price || 0) * +(t.qty || 0), status: 'imported', result: 'imported', currentPrice: +t.price }));
    const sideName = side => ({ 1: 'Abertura LONG', 2: 'Fechamento SHORT', 3: 'Abertura SHORT', 4: 'Fechamento LONG' })[+side] || `Ordem ${side}`;
    const futures = data.futures.filter(t => Number(t.dealVol) > 0).map(t => { const contractSize = contractSizes.get(t.symbol) || 0, fees = (+t.makerFee || 0) + (+t.takerFee || 0), realizedPnl = +t.profit || 0, executedValue = (+t.dealAvgPrice || 0) * (+t.dealVol || 0) * contractSize; return { id: `mexc-futures-${t.orderId}`, imported: true, symbol: String(t.symbol).replace('_', ''), name: t.symbol, source: 'MEXC', strategyName: 'Importado MEXC Futures', vehicle: 'FUTURES', leverage: `${t.leverage || 1}×`, entry: +t.dealAvgPrice, openedAt: new Date(t.createTime).toISOString(), note: `${sideName(t.side)} · ${t.dealVol} contratos · PnL ${num(realizedPnl)}`, side: +t.side, realizedPnl, fees, netPnl: realizedPnl - fees, executedValue, pnlOnNotional: executedValue ? (realizedPnl - fees) / executedValue * 100 : null, status: 'imported', result: 'imported', currentPrice: +t.dealAvgPrice }; });
    const stopsByPosition = new Map(); (data.stopHistory || []).forEach(order => { if (+order.stopLossPrice > 0) stopsByPosition.set(+order.positionId, +order.stopLossPrice); });
    const closedPositions = (data.closedPositions || []).filter(position => +position.state === 3).map(position => { const margin = +position.im || +position.oim || 0, pnlUsd = (+position.realised || 0) + (+position.holdFee || 0), entry = +position.holdAvgPrice || +position.openAvgPrice || 0, stop = stopsByPosition.get(+position.positionId) || 0, quantity = +position.closeVol || +position.holdVol || 0, slRiskUsd = stop && entry && quantity ? Math.abs(entry - stop) * quantity * (contractSizes.get(position.symbol) || 0) : null; return { id: `mexc-position-${position.positionId}`, symbol: position.symbol, direction: +position.positionType === 1 ? 'LONG' : 'SHORT', leverage: +position.leverage || 1, entry, exit: +position.closeAvgPrice || 0, margin, pnlUsd, returnPct: margin ? pnlUsd / margin * 100 : null, stop, slRiskUsd, closedAt: new Date(position.updateTime || position.createTime).toISOString() }; });
    const incoming = [...spot, ...futures], previous = new Map(state.importedTrades.map(t => [t.id, t])), fresh = incoming.filter(t => !previous.has(t.id)); incoming.forEach(t => previous.set(t.id, { ...previous.get(t.id), ...t })); state.importedTrades = [...previous.values()].sort((a, b) => new Date(b.openedAt) - new Date(a.openedAt)); const savedPositions = new Map(state.closedMexcPositions.map(position => [position.id, position])); closedPositions.forEach(position => savedPositions.set(position.id, position)); state.closedMexcPositions = [...savedPositions.values()].sort((a, b) => new Date(b.closedAt) - new Date(a.closedAt)); saveImportedTrades(); saveClosedMexcPositions(); if (!$('mexcRemember').checked) { $('mexcApiKey').value = ''; $('mexcSecret').value = ''; } const warnings = (data.errors || []).length ? ` Aviso: ${data.errors.join(' | ')}` : ''; $('mexcStatus').textContent = `Importação concluída: ${fresh.length} registros novos (${spot.length} spot, ${futures.length} futuros, ${closedPositions.length} posições fechadas).${warnings}`; refreshMexcPositions();
  } catch (error) { $('mexcStatus').textContent = `Não foi possível importar: ${error.message}`; }
  finally { $('mexcImportButton').disabled = false; $('mexcImportButton').textContent = 'Importar MEXC'; }
}
async function historicalCandles(symbol, interval, startTime) {
  const rows = []; let cursor = startTime, guard = 0;
  while (cursor < Date.now() && guard++ < 12) { const batch = await getJson(`${API.binance}/klines?symbol=${symbol}&interval=${interval}&startTime=${cursor}&endTime=${Date.now()}&limit=1000`); if (!batch.length) break; rows.push(...batch); const next = batch.at(-1)[6] + 1; if (next <= cursor || batch.length < 1000) break; cursor = next; }
  return readCandles(rows);
}
const { backtestPortfolio } = SentinelBacktest;
function renderBacktest(trades, startingCapital) {
  trades = trades.filter(trade => !['Rompimento antecipado · EMA 80', 'Rompimento antecipado 2H + confirmação 4H', 'Histórico · Pullback 1H + confluência', 'Pullback 1H + confirmação 4H', 'Pullback 1H + confirmação 2H'].includes(trade.strategyName));
  const closed = trades.filter(t => t.result !== 'open'), wins = closed.filter(t => t.result === 'win'), returns = closed.map(t => t.returnPct), accumulated = returns.reduce((total, value) => total + value, 0), slots = 10, portfolio = backtestPortfolio(trades, startingCapital, slots), chosen = $('backtestReinvest')?.checked ? portfolio.withReinvestment : portfolio.withoutReinvestment;
  const cards = [['Trades', closed.length], ['Acerto', closed.length ? `${num(wins.length / closed.length * 100, 1)}%` : '—'], ['Resultado acumulado', closed.length ? `${accumulated >= 0 ? '+' : ''}${num(accumulated, 1)}%` : '—'], ['Saldo sem reinvestir', closed.length ? `R$ ${num(portfolio.withoutReinvestment)}` : '—'], ['Saldo com reinvestir', closed.length ? `R$ ${num(portfolio.withReinvestment)}` : '—'], ['Capital por trade', `R$ ${num(startingCapital / Math.max(1, Math.min(10, slots)))}`], ['Resultado escolhido', closed.length ? `R$ ${num(chosen)}` : '—'], ['Em aberto', trades.length - closed.length]];
  $('backtestStats').innerHTML = cards.map(([label, value]) => `<div class="stat"><div class="muted">${label}</div><div class="value">${value}</div></div>`).join('');
  if ($('backtestBody')) $('backtestBody').innerHTML = trades.length ? trades.slice().reverse().map(t => `<tr><td>${t.strategyName || 'Setup'}</td><td>${new Date(t.time).toLocaleString('pt-BR')}<div class="sub">${money(t.entry)}</div></td><td>${money(t.stop)}</td><td>${money(t.target)}</td><td>${t.exit ? money(t.exit) : 'Em aberto'}</td><td class="${t.returnPct >= 0 ? 'positive' : 'negative'}">${t.result === 'win' ? 'TP 2R' : t.result === 'loss' ? 'Stop' : 'Aberto'} · ${t.returnPct >= 0 ? '+' : ''}${num(t.returnPct)}%<div class="sub">Máxima: ${Number.isFinite(t.maxRisePct) ? `+${num(t.maxRisePct)}%` : '—'}</div></td></tr>`).join('') : '<tr><td colspan="6" class="empty">Nenhuma entrada preencheu todas as regras no período.</td></tr>';
}
function backtestWindowSummary(trades) {
  const groups = { month: new Map(), week: new Map() };
  trades.filter(t => t.result !== 'open').forEach(t => { const date = new Date(t.time), month = date.toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' }), week = `Semana ${Math.ceil(date.getDate() / 7)}`; [[groups.month, month], [groups.week, week]].forEach(([map, key]) => { const bucket = map.get(key) || { total: 0, wins: 0, returns: [] }; bucket.total++; if (t.result === 'win') bucket.wins++; bucket.returns.push(Number(t.returnPct) || 0); map.set(key, bucket); }); });
  const pick = map => [...map.entries()].map(([label, bucket]) => ({ label, ...bucket, rate: bucket.total ? bucket.wins / bucket.total * 100 : 0, average: bucket.returns.reduce((a, b) => a + b, 0) / Math.max(bucket.returns.length, 1) })).sort((a, b) => (b.rate - a.rate) || (b.total - a.total) || (b.average - a.average))[0];
  return { month: pick(groups.month), week: pick(groups.week) };
}
function renderBacktestComparison(results, capital) {
  results = results.filter(result => !['ema80-breakout', 'pullback-1h-confirm-4h', 'pullback-1h-confirm-2h'].includes(result.strategy));
  const labels = { trend: 'Tendência + pivô', 'aggressive-pullback': 'Pullback 2H + confirmação 4H', 'expansion-retest-2h': 'Experimental · Rompimento + reteste 2H', 'early-breakout-2h-4h': 'Rompimento antecipado 2H + confirmação 4H', 'legacy-pullback-1h': 'Histórico · Pullback 1H + confluência', 'refined-early-ema-rsi': 'Experimental · EMA9/22 + RSI + reteste', 'refined-moderate-ema-rsi': 'Experimental · EMA9/22 + RSI moderado', 'refined-intermediate-ema-rsi': 'Experimental · EMA9/22 + RSI intermediário', 'breakout-30-2h-close': 'Rompimento 30 candles 2H · fechamento', 'breakout-30-2h-retest': 'Rompimento 30 candles 2H · reteste', 'breakout-30-2h-retest-fixed-3': 'Reteste 30 · stop 3% / alvo 3%', 'breakout-30-2h-retest-fixed-4': 'Reteste 30 · stop 3% / alvo 4%', 'breakout-30-2h-retest-fixed-7': 'Reteste 30 · stop 3% / alvo 7%', 'breakout-60-2h-close': 'Rompimento 60 candles 2H · fechamento', 'breakout-60-2h-retest': 'Rompimento 60 candles 2H · reteste', 'breakout-60-2h-retest-fixed-3': 'Reteste 60 · stop 3% / alvo 3%', 'breakout-60-2h-retest-fixed-4': 'Reteste 60 · stop 3% / alvo 4%', 'breakout-60-2h-retest-fixed-7': 'Reteste 60 · stop 3% / alvo 7%', 'ema80-breakout': 'Rompimento antecipado · EMA 80', 'pullback-1h-confirm-4h': 'Pullback 1H + confirmação 4H', 'pullback-1h-confirm-2h': 'Pullback 1H + confirmação 2H' };
  const scored = results.map(result => { const trades = result.trades.filter(t => t.result !== 'open'), wins = trades.filter(t => t.result === 'win'), losses = trades.filter(t => t.result === 'loss'), rate = trades.length ? wins.length / trades.length * 100 : 0, final1 = trades.reduce((value, t) => value * (1 + Math.max(-100, t.returnPct) / 100), capital), windows = backtestWindowSummary(trades); return { result, trades, wins, losses, rate, final1, windows }; }).sort((a, b) => (b.final1 - a.final1) || (b.rate - a.rate));
  $('backtestComparisonBody').innerHTML = scored.map(({ result, trades, wins, losses, rate, final1, windows }, index) => { const reached2 = wins.length, reached3 = trades.filter(t => t.hit3R).length, final2x = trades.reduce((value, t) => value * (1 + Math.max(-100, t.returnPct * 2) / 100), capital); return `<tr class="${index === 0 ? 'backtest-recommendation' : ''}"><td><strong>${labels[result.strategy]}</strong>${index === 0 ? ' ★ RECOMENDADA' : ''}</td><td>${trades.length}</td><td class="result-win">${wins.length}</td><td class="result-loss">${losses.length}</td><td>${trades.length ? `${num(rate, 1)}%` : '—'}</td><td>${reached2}${trades.length ? ` (${num(reached2 / trades.length * 100, 1)}%)` : ''}</td><td>${reached3}${trades.length ? ` (${num(reached3 / trades.length * 100, 1)}%)` : ''}</td><td class="${final1 >= capital ? 'positive' : 'negative'}">R$ ${num(final1)} (${final1 >= capital ? '+' : ''}${num((final1 / capital - 1) * 100, 1)}%)</td><td class="${final2x >= capital ? 'positive' : 'negative'}">R$ ${num(final2x)} (${final2x >= capital ? '+' : ''}${num((final2x / capital - 1) * 100, 1)}%)</td><td>${windows.month ? `${windows.month.label} · ${num(windows.month.rate, 1)}%` : '—'}</td><td>${windows.week ? `${windows.week.label} · ${num(windows.week.rate, 1)}%` : '—'}</td><td><strong>${String(result.timeframe || '—').toUpperCase()}</strong></td></tr>`; }).join('');
  document.querySelectorAll('#backtestComparisonBody tr').forEach((row, index) => { const data = scored[index]; if (!data) return; const anchor = row.children[9]; [5, 4, 3].forEach(lev => { const final = data.trades.reduce((value, trade) => value * (1 + Math.max(-100, trade.returnPct * lev) / 100), capital), cell = document.createElement('td'); cell.className = final >= capital ? 'positive' : 'negative'; cell.textContent = `R$ ${num(final)} (${final >= capital ? '+' : ''}${num((final / capital - 1) * 100, 1)}%)`; row.insertBefore(cell, anchor); }); });
  const slots = 10;
  document.querySelectorAll('#backtestComparisonBody tr').forEach((row, index) => { const data = scored[index]; if (!data) return; [1, 2, 3, 4, 5].forEach((multiplier, offset) => { const cell = row.children[7 + offset]; if (!cell) return; const result = backtestPortfolio(data.trades, capital, slots, multiplier).withReinvestment; cell.textContent = `R$ ${num(result)} (${result >= capital ? '+' : ''}${num((result / capital - 1) * 100, 1)}%)`; }); });
  const ranked = scored.slice().sort((a, b) => backtestPortfolio(b.trades, capital, slots).withReinvestment - backtestPortfolio(a.trades, capital, slots).withReinvestment), best = ranked[0]; $('backtestStrategyRecommendation').textContent = best && best.trades.length ? `★ Mais recomendada: ${labels[best.result.strategy]}, no ${String(best.result.timeframe || 'tempo selecionado').toUpperCase()} (${num(best.rate, 1)}% de acerto e resultado com alocação de ${num((backtestPortfolio(best.trades, capital, slots).withReinvestment / capital - 1) * 100, 1)}%).` : 'Sem trades suficientes para recomendar uma estratégia.'; if (best && best.trades.length) { const avgWin = best.trades.filter(t => t.result === 'win'), avgLoss = best.trades.filter(t => t.result === 'loss'); $('backtestStrategyRecommendation').textContent += ` Média: ganhos +${num(avgWin.reduce((s, t) => s + t.returnPct, 0) / Math.max(1, avgWin.length))}% · perdas ${num(avgLoss.reduce((s, t) => s + t.returnPct, 0) / Math.max(1, avgLoss.length))}%.`; }
}
function renderBacktestAssetSummary(results, capital) {
  results = results.filter(result => !['ema80-breakout', 'legacy-pullback-1h', 'pullback-1h-confirm-4h', 'pullback-1h-confirm-2h'].includes(result.strategy));
  const groups = new Map(); results.flatMap(result => result.trades).forEach(trade => { const bucket = groups.get(trade.asset) || { trades: [] }; bucket.trades.push(trade); groups.set(trade.asset, bucket); });
  const leverage = [1, 2, 3, 4, 5], rowsData = [...groups.entries()].map(([asset, bucket]) => { const closed = bucket.trades.filter(trade => trade.result !== 'open').sort((a, b) => a.time - b.time), wins = closed.filter(trade => trade.result === 'win'), losses = closed.filter(trade => trade.result === 'loss'), final = lev => closed.reduce((value, trade) => value * (1 + Math.max(-100, trade.returnPct * lev) / 100), capital), best = leverage.reduce((chosen, lev) => final(lev) > final(chosen) ? lev : chosen, 1); return { asset, closed, wins, losses, final, best }; }).sort((a, b) => b.final(1) - a.final(1));
  const slots = 10;
  rowsData.forEach(row => { row.final = lev => backtestPortfolio(row.closed, capital, slots, lev).withReinvestment; row.best = [1, 2, 3].reduce((chosen, lev) => row.final(lev) > row.final(chosen) ? lev : chosen, 1); });
  const rows = rowsData.map((row, index) => `<tr class="${index === 0 ? 'backtest-recommendation' : ''}"><td><strong>${row.asset.replace('USDT', '')}</strong>${index === 0 ? ' ★ RECOMENDADO' : ''}</td><td>${row.closed.length}</td><td class="positive">${row.wins.length}</td><td class="negative">${row.losses.length}</td><td>${row.closed.length ? `${num(row.wins.length / row.closed.length * 100, 1)}%` : '—'}</td><td>R$ ${num(row.final(1))}</td><td>${row.best}× · R$ ${num(row.final(row.best))}</td></tr>`);
  $('backtestAssetsBody').innerHTML = rows.length ? rows.join('') : '<tr><td colspan="7" class="empty">Nenhum ativo gerou entradas no período.</td></tr>';
  $('backtestAssetRecommendation').textContent = rowsData.length ? `★ Melhor retorno composto em 1×: ${rowsData[0].asset.replace('USDT', '')}.` : 'Sem ativos com entradas suficientes.';
}
function renderBacktestPeriodSummary(trades) {
  const groups = new Map();
  trades.filter(trade => trade.result !== 'open').forEach(trade => { const date = new Date(trade.time), month = date.toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' }), week = `Semana ${Math.ceil(date.getDate() / 7)} do mês`; [month, week].forEach(key => { const bucket = groups.get(key) || { wins: 0, losses: 0, returns: [] }; if (trade.result === 'win') bucket.wins++; if (trade.result === 'loss') bucket.losses++; bucket.returns.push(trade.returnPct); groups.set(key, bucket); }); });
  const rowsData = [...groups.entries()].map(([period, bucket]) => { const total = bucket.wins + bucket.losses, rate = total ? bucket.wins / total * 100 : 0, avg = bucket.returns.length ? bucket.returns.reduce((a, b) => a + b, 0) / bucket.returns.length : 0; return { period, bucket, total, rate, avg }; }).sort((a, b) => (b.rate - a.rate) || (b.total - a.total) || (b.avg - a.avg));
  const rows = rowsData.map((row, index) => `<tr class="${index === 0 ? 'backtest-recommendation' : ''}"><td>${row.period}${index === 0 ? ' ★ MELHOR JANELA' : ''}</td><td>${row.total}</td><td class="positive">${row.bucket.wins}</td><td class="negative">${row.bucket.losses}</td><td>${row.total ? `${num(row.rate, 1)}%` : '—'}</td><td class="${row.avg >= 0 ? 'positive' : 'negative'}">${row.bucket.returns.length ? `${row.avg >= 0 ? '+' : ''}${num(row.avg)}%` : '—'}</td></tr>`);
  $('backtestPeriodsBody').innerHTML = rows.length ? rows.join('') : '<tr><td colspan="6" class="empty">Nenhuma entrada fechada para analisar.</td></tr>';
  $('backtestPeriodRecommendation').textContent = rowsData.length ? `★ Prioridade estatística: ${rowsData[0].period} (${num(rowsData[0].rate, 1)}% de acerto; ${rowsData[0].total} trades).` : 'Sem entradas fechadas para recomendar uma janela.';
}
function renderBacktestAudit(results, capital) {
  const labels = { trend: 'Tendência + pivô', 'aggressive-pullback': 'Atual · Pullback 2H + confirmação 4H', 'legacy-pullback-1h': 'Histórico · Pullback 1H + confluência', 'refined-early-ema-rsi': 'Experimental · EMA9/22 + RSI + reteste', 'refined-moderate-ema-rsi': 'Experimental · EMA9/22 + RSI moderado' };
  const rows = results.filter(result => ['trend', 'aggressive-pullback', 'legacy-pullback-1h'].includes(result.strategy)).map(result => { const closed = result.trades.filter(trade => trade.result !== 'open'), wins = closed.filter(trade => trade.result === 'win'), legacy = closed.reduce((value, trade) => value * (1 + Math.max(-100, trade.returnPct) / 100), capital), current = backtestPortfolio(closed, capital, 10, 1).withReinvestment; return `<tr><td><strong>${labels[result.strategy] || result.strategy}</strong></td><td>${String(result.timeframe).toUpperCase()}</td><td>${closed.length}</td><td>${closed.length ? `${num(wins.length / closed.length * 100, 1)}%` : '—'}</td><td class="negative">R$ ${num(legacy)} (${legacy >= capital ? '+' : ''}${num((legacy / capital - 1) * 100, 1)}%)</td><td class="positive">R$ ${num(current)} (${current >= capital ? '+' : ''}${num((current / capital - 1) * 100, 1)}%)</td></tr>`; });
  if ($('backtestAuditBody')) $('backtestAuditBody').innerHTML = rows.length ? rows.join('') : '<tr><td colspan="6" class="empty">Nenhuma combinação gerou trades fechados.</td></tr>';
}
const renderBacktestComparisonBase = renderBacktestComparison;
renderBacktestComparison = (results, capital) => { renderBacktestComparisonBase(results, capital); document.querySelectorAll('#backtestComparisonBody tr').forEach(row => { if (row.children[0]?.textContent.startsWith('undefined')) row.children[0].textContent = 'Pullback 2H · diário flexível'; }); renderBacktestAudit(results, capital); document.querySelectorAll('#backtestAuditBody tr').forEach(row => { if (row.children[0]?.textContent.startsWith('undefined')) row.children[0].textContent = 'Pullback 2H · diário flexível'; }); };
async function simulateBacktestAsset(symbol, start, end, timeframe, strategies) {
  strategies = strategies.filter(strategy => ['trend', 'aggressive-pullback', 'flexible-pullback-2h', 'legacy-pullback-1h', 'refined-early-ema-rsi', 'refined-moderate-ema-rsi', 'refined-intermediate-ema-rsi', 'breakout-30-2h-close', 'breakout-30-2h-retest', 'breakout-30-2h-retest-fixed-3', 'breakout-30-2h-retest-fixed-4', 'breakout-30-2h-retest-fixed-7', 'breakout-60-2h-close', 'breakout-60-2h-retest', 'breakout-60-2h-retest-fixed-3', 'breakout-60-2h-retest-fixed-4', 'breakout-60-2h-retest-fixed-7', 'expansion-retest-2h'].includes(strategy));
  const dayMs = 86400000, days = Math.max(7, Math.ceil((end - start) / dayMs));
  const [week, day, h4, h2, h1] = await Promise.all([historicalCandles(symbol, '1w', start - 2600 * dayMs), historicalCandles(symbol, '1d', start - (days + 230) * dayMs), historicalCandles(symbol, '4h', start - (days + 60) * dayMs), historicalCandles(symbol, '2h', start - (days + 35) * dayMs), historicalCandles(symbol, '1h', start - (days + 25) * dayMs)]);
  return SentinelBacktest.simulate({'1w':week,'1d':day,'4h':h4,'2h':h2,'1h':h1},symbol,start,end,timeframe,strategies,{minScore:+$('minScore').value}).map(result => { if (result.strategy === 'flexible-pullback-2h') result.trades.forEach(trade => { trade.strategyName = 'Pullback 2H · diário flexível'; }); return result; });
}
function selectedBacktestFilters(name, allValues) {
  const selected = [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(input => input.value);
  return selected.length ? selected : allValues;
}
function syncBacktestFilterAll(group) {
  const all = group.querySelector('[data-backtest-all]'), options = [...group.querySelectorAll('input[name]')];
  if (!all || !options.length) return;
  all.checked = options.every(input => input.checked);
}
function configureBacktestFilters() {
  document.querySelectorAll('[data-backtest-all]').forEach(all => all.addEventListener('change', () => {
    const group = all.closest('.filter-group'); group.querySelectorAll('input[name]').forEach(input => { input.checked = all.checked; });
  }));
  document.querySelectorAll('.filter-group input[name]').forEach(input => input.addEventListener('change', () => syncBacktestFilterAll(input.closest('.filter-group'))));
}
function enforceOfficialBacktestSetups() {
  const allowed = new Set(['trend', 'aggressive-pullback', 'flexible-pullback-2h']);
  document.querySelectorAll('#backtestStrategyFilters input[name="backtestStrategy"]').forEach(input => { if (!allowed.has(input.value)) input.closest('label')?.remove(); });
  const all = document.querySelector('#backtestStrategyFilters [data-backtest-all]'); if (all) all.checked = true;
}
async function runBacktest() {
  const symbols = $('backtestSymbol').value.split(/[\s,;]+/).map(value => value.trim().toUpperCase()).filter(Boolean).map(value => value.endsWith('USDT') ? value : `${value}USDT`).filter((value, index, list) => list.indexOf(value) === index), startInput = $('backtestStartDate').value, endInput = $('backtestEndDate').value, start = new Date(`${startInput}T00:00:00`).getTime(), end = new Date(`${endInput}T23:59:59`).getTime(), strategies = selectedBacktestFilters('backtestStrategy', ['trend', 'aggressive-pullback']), timeframes = selectedBacktestFilters('backtestTimeframe', ['1h', '2h', '4h']), capital = +$('backtestCapital').value;
  if (!symbols.length || symbols.some(symbol => !/^[A-Z0-9]{5,18}$/.test(symbol))) { $('backtestStatus').textContent = 'Informe pares válidos, separados por vírgula, como LINK, NEAR, ETH e SOL.'; return; }
  if (!Number.isFinite(start) || !Number.isFinite(end) || start >= end) { $('backtestStatus').textContent = 'Escolha datas válidas: a data inicial deve ser anterior à data final.'; return; }
  if (!Number.isFinite(capital) || capital <= 0) { $('backtestStatus').textContent = 'Informe um capital inicial maior que zero.'; return; }
  $('backtestButton').disabled = true; $('backtestButton').textContent = 'Carregando candles…'; $('backtestStatus').textContent = `Baixando dados reais de ${symbols.length} ativo(s)…`;
  try { const allResults = [], failedSymbols = []; for (const symbol of symbols) { try { allResults.push(...await simulateBacktestAsset(symbol, start, end, timeframes, strategies)); } catch (error) { failedSymbols.push(`${symbol}: ${error.message}`); } } const grouped = strategies.map(strategy => { const candidates = timeframes.map(tf => { const parts = allResults.filter(result => result.strategy === strategy && result.timeframe === tf), trades = parts.flatMap(result => result.trades).sort((a, b) => a.time - b.time), closed = trades.filter(t => t.result !== 'open'), wins = closed.filter(t => t.result === 'win'), final1 = closed.reduce((value, t) => value * (1 + Math.max(-100, t.returnPct) / 100), capital); return { strategy, timeframe: tf, trades, evaluated: parts.reduce((sum, result) => sum + result.evaluated, 0), candidates: parts.reduce((sum, result) => sum + result.candidates, 0), rate: closed.length ? wins.length / closed.length * 100 : 0, final1 }; }); return candidates.sort((a, b) => (b.final1 - a.final1) || (b.rate - a.rate))[0] || { strategy, timeframe: timeframes[0], trades: [], evaluated: 0, candidates: 0 }; }); const allTrades = grouped.flatMap(result => result.trades).sort((a, b) => a.time - b.time); renderBacktest(allTrades, capital); renderBacktestComparison(grouped, capital); renderBacktestAssetSummary(grouped, capital); renderBacktestPeriodSummary(allTrades); const totalEvaluated = grouped.reduce((sum, result) => sum + result.evaluated, 0); $('backtestStatus').textContent = `${symbols.length} ativo(s), ${startInput} até ${endInput}, contexto macro 1D/4H e ${timeframes.length === 4 ? 'comparação automática de 1H, 2H, 4H e Diário' : `gatilhos ${timeframes.map(value => value.toUpperCase()).join(', ')}`}. ${totalEvaluated} avaliações.${failedSymbols.length ? ` Falhas: ${failedSymbols.slice(0, 3).join(' | ')}` : ''} O saldo 2× reinveste cada resultado; cálculo sem taxas, slippage, funding ou liquidação real.`; } catch (error) { $('backtestStatus').textContent = `Não foi possível concluir o backtest: ${error.message}`; } finally { $('backtestButton').disabled = false; $('backtestButton').textContent = 'Simular setup'; }
}
const settings = loadSettings(); const formatBacktestDate = date => { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 10); }; const backtestToday = new Date(), backtestStart = new Date(backtestToday); backtestStart.setDate(backtestStart.getDate() - 30); if ($('backtestStartDate') && !$('backtestStartDate').value) $('backtestStartDate').value = formatBacktestDate(backtestStart); if ($('backtestEndDate') && !$('backtestEndDate').value) $('backtestEndDate').value = formatBacktestDate(backtestToday); const allowedRefresh = ['5', '10', '20', '30', '60', '120', '180', '240']; $('autoRefresh').value = allowedRefresh.includes(String(settings.autoRefresh)) ? String(settings.autoRefresh) : '5'; $('browserAlerts').checked = Boolean(settings.browserAlerts);
const savedMexc = loadMexcCredentials(); if (savedMexc.remember) { $('mexcApiKey').value = savedMexc.apiKey || ''; $('mexcSecret').value = savedMexc.secret || ''; $('mexcSpotSymbol').value = savedMexc.spotSymbol || 'BTCUSDT'; $('mexcRemember').checked = true; }
$('scanButton').addEventListener('click', scan); $('entryForm').addEventListener('submit', recordTrade); $('refreshTracking').addEventListener('click', refreshTracking); $('backtestButton').addEventListener('click', runBacktest); $('mexcImportButton').addEventListener('click', importMexcTrades); $('mexcForgetButton').addEventListener('click', forgetMexcCredentials); $('mexcPositionsButton').addEventListener('click', refreshMexcPositions); $('mexcLiveAuto').addEventListener('change', configureMexcLive); $('mexcHistoryAuto').addEventListener('change', configureMexcHistoryAuto); $('mexcMinResult').addEventListener('input', renderMexcMetrics); $('strategySelect').addEventListener('change', updateStrategyHelp); if ($('refreshSignalHistory')) $('refreshSignalHistory').addEventListener('click', () => refreshSignalHistory().catch(() => { if ($('signalHistoryStatus')) $('signalHistoryStatus').textContent = 'Não foi possível atualizar os sinais agora.'; })); $('autoRefresh').addEventListener('change', configureAutoRefresh); $('browserAlerts').addEventListener('change', async () => { if ($('browserAlerts').checked && 'Notification' in window && Notification.permission !== 'granted') { const permission = await Notification.requestPermission(); if (permission !== 'granted') $('browserAlerts').checked = false; } saveSettings(); }); enforceOfficialBacktestSetups(); configureBacktestFilters(); configureAutoRefresh(); configureMexcLive(); configureMexcHistoryAuto(); updateStrategyHelp(); renderSignals(); renderSignalHistory(); renderTrades(); renderImportedTrades(); renderMexcMetrics(); renderMexcPositions(); renderStats();

